[package]
name = "dabih"
description = "Command Line Interface for dabih"
authors = ["Michael Huttner<michael@mhuttner.com>"]
version = "1.5.1"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/spang-lab/dabih"
repository = "https://github.com/spang-lab/dabih"
keywords = ["cli", "dabih"]
categories = ["command-line-utilities"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
base64 = "0.21.2"
clap = { version = "4.3.21", features = ["derive"] }
crypto = "0.5.1"
flate2 = "1.0.27"
glob = "0.3.1"
home = "0.5.5"
inquire = "0.6.2"
openssl = "0.10.56"
pbr = "1.1.1"
reqwest = { version = "0.11.18", features = ["json", "multipart"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
tokio = { version = "1.29.1", features = ["full"] }
url = "2.4.0"
zip = "0.6.6"
