server:
  port: 3001

admins:
  subs: []
  groups:
    - dabih

crypto:
  rootKeys: []

# Configure where to store temporary data
ephemeral:
  adapter: redis
  url: redis://redis.dabih:6379

database:
  dialect: postgres
  logging: false
  host: YOUR_POSTGRES_HOST
  port: 5432
  database: YOUR_DATABASE_NAME
  username: YOUR_DATABASE_USER

storage:
  backend: local
  path: /usr/src/app/data
