apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dabih-data-pvc
  namespace: dabih
spec:
  storageClassName: default
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

