name: Publish Crates.io cli crate

on:
  push:
    tags:
      - "v*"

jobs:
  binaries:
    name: Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
            x86_64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
            x86_64-pc-windows-gnu,
            #x86_64-apple-darwin,
            #aarch64-apple-darwin,
            #aarch64-pc-windows-msvc,
          ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install the windows toolchain.
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build the package
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --manifest-path cli/Cargo.toml --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          # tmp
          cd cli/target/${{ matrix.target }}/release          
          if [ "${{ matrix.target }}" = "x86_64-pc-windows-gnu" ]; then
            zip ../../../dabih-${{ matrix.target }}.zip dabih.exe
          else
            tar czvf ../../../dabih-${{ matrix.target }}.tar.gz dabih
          fi
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          name: Dabih CLI
          files: "cli/dabih*"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo publish
        working-directory: ./cli
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
