name: Publish Crates.io cli crate

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [linux, macos, arm_macos, windows]
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-pc-windows-gnu]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build CLI for ${{ matrix.target }}
      run: cargo build --manifest-path cli/Cargo.toml --release --target ${{ matrix.target }}

    - name: Archive Artifact
      run: |
        cd cli
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          7z a -tzip dabih_${{ matrix.os }}.zip target/${{ matrix.target }}/release/dabih.exe
        else
          tar czf dabih_${{ matrix.os }}.tar.gz -C target/${{ matrix.target }}/release .
        fi
        cd -

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: cli/dabih_${{ matrix.os }}.zip

    - name: Publish Release ID
      run: echo "RELEASE_ID_${{ matrix.os}}=${{ steps.create_release.outputs.id }}" >> $GITHUB_ENV

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cargo publish
        working-directory: ./cli
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
